"""Generate the per-fold strategy subclasses and the launcher for the walk-forward runs.

Each fold/variant becomes a uniquely named subclass of FundingSkewMomentum1m with the
parameter defaults baked in, so the runs are concurrency-safe: no shared params file, and
each exported result is identifiable by its strategy name.
"""
import json
from pathlib import Path

import pandas as pd

WORK = Path("/root/freqtrade/user_data/niche_work")
OUT = Path("/root/freqtrade/user_data/strategies/wf_funding")
DEFAULT = dict(fr=40.0, streak=1, stop=15, hold=235)
MONTHS = {"2026-02": "20260201-20260301", "2026-03": "20260301-20260401",
          "2026-04": "20260401-20260501", "2026-05": "20260501-20260601",
          "2026-06": "20260601-20260701", "2026-07": "20260701-20260801",
          "2026-08": "20260801-20260817"}

TEMPLATE = '''"""Walk-forward fold {month}, {variant}. Generated by scripts/niche_funding_wf_runs.py."""
import sys

sys.path.insert(0, "/root/freqtrade/user_data/strategies")

from freqtrade.strategy import BooleanParameter, DecimalParameter, IntParameter

from FundingSkewMomentum1m import FundingSkewMomentum1m


class {cls}(FundingSkewMomentum1m):
    fr_threshold = DecimalParameter(30.0, 100.0, default={fr}, decimals=0, space="buy")
    min_streak = IntParameter(0, 3, default={streak}, space="buy")
    close_stop = DecimalParameter(0.06, 0.25, default={stop}, decimals=2, space="sell")
    hold_minutes = IntParameter(60, 235, default={hold}, space="sell")
    allow_long = BooleanParameter(default={allow_long}, space="buy")
'''


def main():
    wf = pd.read_csv(WORK / "walkforward.csv")
    OUT.mkdir(parents=True, exist_ok=True)
    runs = []
    for month, timerange in MONTHS.items():
        for allow_long in (False, True):
            for mode in ("def", "sel"):
                if mode == "def":
                    cfg = DEFAULT
                else:
                    row = wf[(wf.month == month) & (wf.allow_long == allow_long)].iloc[0]
                    cfg = json.loads(row.pick_total)
                side = "long" if allow_long else "short"
                cls = f"FSM_{month.replace('-', '')}_{mode}_{side}"
                (OUT / f"{cls}.py").write_text(TEMPLATE.format(
                    month=month, variant=f"{mode} / {side}", cls=cls,
                    fr=float(cfg["fr"]), streak=int(cfg["streak"]),
                    stop=cfg["stop"] / 100, hold=int(cfg["hold"]), allow_long=allow_long))
                runs.append(dict(cls=cls, timerange=timerange, month=month,
                                 mode=mode, allow_long=allow_long, **cfg))
    pd.DataFrame(runs).to_csv(WORK / "wf_runs.csv", index=False)
    print(f"generated {len(runs)} strategies in {OUT}")


if __name__ == "__main__":
    main()
